AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fetch_google_trends_image

Globals:
  Function:
    Timeout: 3

Parameters:
  DynamoDbTableArn:
    Type: String

Resources:
  FetchGoogleTrends:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 100
      PackageType: Image
      Architectures:
        - arm64
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0,15,30,45 * * * ? *)
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
              Resource: !Ref DynamoDbTableArn
    Metadata:
      DockerTag: nodejs20.x-v1
      DockerContext: .
      Dockerfile: Dockerfile
